site_name: Fortify DevOps Guide
theme: cerulean
nav:
  - Home: 'index.md'
  - CI/CD: 
    - Gitlab: 'integrations/cicd/gitlab.md'
    - Github: 'integrations/cicd/github.md'
    - Jenkins: 'integrations/cicd/jenkins.md'

  - IDE: 
    - IntelliJ: 'integrations/ide/intellij.md'
    - Visual Studio Code: 'integrations/ide/vscode.md'

  - BugTracking:
    - Azure Devops: 'integrations/bugtracking/ado.md'
    - GitLab Security Dashboard: 'integrations/bugtracking/gitlab.md'
    - Jira: 'integrations/bugtracking/jira.md'


markdown_extensions:
    - attr_list
    - md_in_html
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
    - mkdocs-video